### ISSUE TITLE
Add Lighter

### ISSUE THREAD

**Issue by zoedberg** [bcongdon/awesome-lightning-network#35]
I would like to add Lighter (https://gitlab.com/inbitcoin/lighter) to this list, but I can't decide which section fits it best.

Lighter is a LN node wrapper, which allows easier writing of LN-based software by abstracting away the details of the underlying implementation.

Ideally, it would fall in a _tooling_ section.
What do you think about it?

**Comment by thorie7912** [comment]
Could it go under `libraries` ?

**Comment by bcongdon** [comment]
Yup, this could definitely fit under libraries 😄
